### ISSUE TITLE
CLI display incompatibilities with Windows Powershell

### ISSUE THREAD

**Issue by weeco** [nestjs/nest-cli#103]
Some responses are apparently incompatible with the Win10 Powershell as shown in the below screenshot:

![](https://i.imgur.com/JgacGjJ.png)

**Comment by ThomRick** [comment]
Oh we may have to manage i18n with the emojis !!! XD
I close #102 because it's same issue.

**Comment by ThomRick** [comment]
Hey @weeco 
Could you increase cli version and try again ?
I used commander instead of caporaljs I hope it is fixed...

**Comment by ThomRick** [comment]
No feedbacks... close issue

**Comment by weeco** [comment]
@ThomRick I just gave it another try and along with other issues the display issue is still existent: 

https://i.imgur.com/r1J2eO4.png
